# Generated by Django 4.1.2 on 2023-06-24 00:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("packagedb", "0067_alter_resource_md5_alter_resource_sha1_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="resource",
            options={},
        ),
        migrations.AddField(
            model_name="package",
            name="package_sets",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.UUIDField(blank=True, null=True),
                blank=True,
                default=list,
                help_text="A list of package_set UUIDs that identifies which groups this Package is related to",
                null=True,
                size=None,
            ),
        ),
    ]
